### ISSUE TITLE
401 Client Error: Unauthorized

### ISSUE THREAD

**Issue by rome138** [sonya75/NikeAccountGenerator#3]
401 Client Error: Unauthorized for url: https://api.nike.com/idn/shim/oauth/2.0/

script is broken now, is there a fix ? thx

**Comment by Ronenic** [comment]
Yeah it seems as if Nike changed something. An update to the script would be very much appreciated

**Comment by ceejjaayy** [comment]
Yup I am having the same problem

**Comment by sonya75** [comment]
The error is with the registration request. You get 403 forbidden when sending the request. To avoid the error, you have to pass akamai's bot detection before sending the request. The 401 error shows up only because the registration fails and the login doesn't work. I have a version of the script that passes the bot detection. But I am not going to post that in github.

**Comment by ZachWhitford** [comment]
@sonya75 what would you suggest we modify on the script to pass the bot detection algorithm

**Comment by sonya75** [comment]
I would suggest reading the javascript that does the bot detection. Figuring out exactly what it generates. Then randomize that value properly so that it actually looks like the sensor data was generated from human interaction and then send the request for bot detection from the script to get the proper cookies.
