### ISSUE TITLE
403 Client Error: Forbidden for url

### ISSUE THREAD

**Issue by dukai1011** [sonya75/NikeAccountGenerator#9]
> 403 Client Error: Forbidden for url: https://unite.nike.com/access/users/v1?appVersion=389&experienceVersion=325&uxid=com.nike.commerce.nikedotcom.web&locale=en_US&backendEnvironment=identity&browser=Google%20Inc.&os=undefined&mobile=false&native=false&visit=2&visitor=fbf3e792-4849-44c1-b960-d2fe3a2f292a&language=en-US
Trying to get abck cookie

Yesterday was good, today I got this.

<img width="667" alt="screen shot 2018-03-29 at 5 43 33 pm" src="https://user-images.githubusercontent.com/9975427/38117075-bae06820-3378-11e8-86bb-7d0f4e6050b0.png">

**Comment by Gburshaly** [comment]
The accounts I generate say they succesful while creating but most of them are not verified..

**Comment by dukai1011** [comment]
@Gburshaly check your getsmscode.com account balance and SMS history to ensure you gets the code

**Comment by sonya75** [comment]
Akamai has indeed patched the bot detection bypass. I won't disclose the trick they pulled since it was kind of a last resort for them. I will post it once they have created a new bot detection javascript. You can still use nikegenfast.py. But last I heard, Nike is banning the accounts made with nikegenfast.py.

**Comment by Gburshaly** [comment]
I have balance and get sms. But like 3/4 of the accounts I created are not verified.
